<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, formatTime, notifyError, parseJSON, pretty } from '../api'
import { businessStatuses, categories, connectionStatuses, dataStatuses, deviceRoles, enabledStatuses, label, tagType } from '../labels'
const emit=defineEmits(['navigate'])
const products=ref([]), registry=ref([]), unregistered=ref([]), loading=ref(false), dialog=ref(false), credentialDialog=ref(false), credential=ref({})
const blank=()=>({id:'',code:'',name:'',productId:'',deviceRole:'DIRECT',gatewayId:'',status:'ENABLED',tags:pretty({buildingId:'A',deviceType:'smoke'}),description:''})
const form=reactive(blank())
const gateways=computed(()=>registry.value.filter(x=>roleOf(x.device)==='GATEWAY'))
function roleOf(device){return device.deviceRole||(products.value.find(x=>x.id===device.productId)?.category==='gateway'?'GATEWAY':'DIRECT')}
function productName(id){return products.value.find(x=>x.id===id)?.name||id}
function deviceName(id){return registry.value.find(x=>x.device.id===id)?.device.name||id||'未设置'}
function relation(row){const r=roleOf(row.device);return r==='GATEWAY'?`${row.childCount||0} 个子设备`:r==='CHILD'?`所属网关：${deviceName(row.device.gatewayId)}`:'独立接入'}
async function load(){loading.value=true;try{const [p,runtime,managed]=await Promise.all([api('/api/v1/products'),api('/api/v1/devices'),api('/api/v1/device-registry')]);products.value=p.items||[];registry.value=managed.items||[];const ids=new Set(registry.value.map(x=>x.device.id));unregistered.value=(runtime.items||[]).filter(x=>!ids.has(x.deviceId))}catch(e){notifyError(e)}finally{loading.value=false}}
function open(device){Object.assign(form,blank(),device?{...device,code:device.id,tags:pretty(device.tags||{})}:{});dialog.value=true}
async function save(){try{const v={...form,id:form.id||form.code,tags:parseJSON(form.tags,'标签 JSON')};delete v.code;const editing=registry.value.some(x=>x.device.id===v.id),d=await api(editing?`/api/v1/device-registry/${encodeURIComponent(v.id)}`:'/api/v1/device-registry',{method:editing?'PUT':'POST',body:JSON.stringify(v)});dialog.value=false;if(d.credential)showCredential(d.credential);ElMessage.success('设备已保存');load()}catch(e){notifyError(e)}}
async function register(id){try{const d=await api(`/api/v1/discovered-devices/${encodeURIComponent(id)}/register`,{method:'POST',body:'{}'});if(d.credential)showCredential(d.credential);ElMessage.success('设备已注册并移入正式设备列表');load()}catch(e){notifyError(e)}}
async function rotate(id){try{await ElMessageBox.confirm('轮换后旧凭证立即失效，确定继续？','轮换设备凭证',{type:'warning'});const d=await api(`/api/v1/device-registry/${encodeURIComponent(id)}/credentials`,{method:'POST',body:'{}'});showCredential(d.credential);load()}catch(e){if(e!=='cancel')notifyError(e)}}
function showCredential(value){credential.value=value;credentialDialog.value=true}
async function copyCredential(){await navigator.clipboard.writeText(`X-Device-Key: ${credential.value.accessKey}\nX-Device-Secret: ${credential.value.secret}`);ElMessage.success('凭证已复制')}
function guide(id){emit('navigate','integration',{deviceId:id})}
const realtime=()=>load()
onMounted(()=>{load();window.addEventListener('iot:realtime',realtime)})
onBeforeUnmount(()=>window.removeEventListener('iot:realtime',realtime))
</script>
<template><div class="page-toolbar"><el-button type="primary" @click="open()">注册设备</el-button><el-button @click="load">刷新</el-button></div>
<el-card shadow="never" class="surface-card table-card"><el-table v-loading="loading" :data="registry" stripe><el-table-column label="设备" min-width="190"><template #default="{row}"><b>{{row.device.name}}</b><small class="subline">{{row.device.id}}</small></template></el-table-column><el-table-column label="产品" min-width="160"><template #default="{row}">{{productName(row.device.productId)}}</template></el-table-column><el-table-column label="设备角色" width="120"><template #default="{row}"><el-tag round>{{label(deviceRoles,roleOf(row.device),'直接设备')}}</el-tag><small v-if="row.device.autoRegistered" class="subline">网关自动注册</small></template></el-table-column><el-table-column label="所属关系" min-width="150"><template #default="{row}">{{relation(row)}}</template></el-table-column><el-table-column label="启用状态" width="105"><template #default="{row}"><el-tag :type="tagType(row.device.status)" round>{{label(enabledStatuses,row.device.status)}}</el-tag></template></el-table-column><el-table-column label="运行状态" width="105"><template #default="{row}"><el-tag :type="tagType(row.runtimeState?.businessStatus)" round>{{label(businessStatuses,row.runtimeState?.businessStatus||'NEVER_SEEN')}}</el-tag></template></el-table-column><el-table-column label="接入密钥" min-width="190"><template #default="{row}"><code>{{row.device.accessKey}}</code><small class="subline">设备密钥 ···{{row.device.secretHint}}</small></template></el-table-column><el-table-column label="最后活跃" min-width="160"><template #default="{row}">{{formatTime(row.runtimeState?.lastSeenAt)}}</template></el-table-column><el-table-column label="操作" fixed="right" width="205"><template #default="{row}"><el-button link type="primary" @click="guide(row.device.id)">接入</el-button><el-button link type="primary" @click="open(row.device)">编辑</el-button><el-button link type="warning" @click="rotate(row.device.id)">轮换凭证</el-button></template></el-table-column><template #empty><el-empty description="还没有注册设备，请先创建协议包和产品" /></template></el-table></el-card>
<el-card shadow="never" class="surface-card table-card top-gap"><template #header><div class="card-header"><strong>未注册设备</strong><small>仅显示已经上报过数据、但尚未纳入正式设备管理的设备</small></div></template><el-table :data="unregistered" stripe><el-table-column prop="deviceId" label="设备 ID" min-width="190" /><el-table-column label="产品" min-width="150"><template #default="{row}">{{productName(row.productId)}}</template></el-table-column><el-table-column label="业务状态" width="105"><template #default="{row}"><el-tag :type="tagType(row.businessStatus)" round>{{label(businessStatuses,row.businessStatus)}}</el-tag></template></el-table-column><el-table-column label="连接状态" width="110"><template #default="{row}">{{label(connectionStatuses,row.connectionStatus)}}</template></el-table-column><el-table-column label="数据状态" width="110"><template #default="{row}">{{label(dataStatuses,row.dataStatus)}}</template></el-table-column><el-table-column label="最后活跃" min-width="170"><template #default="{row}">{{formatTime(row.lastSeenAt)}}</template></el-table-column><el-table-column label="操作" width="110"><template #default="{row}"><el-button @click="register(row.deviceId)">一键注册</el-button></template></el-table-column><template #empty><el-empty description="当前没有未注册设备" /></template></el-table></el-card>

<el-dialog v-model="dialog" :title="form.id?'编辑设备':'注册设备'" width="min(640px, 94vw)"><el-form :model="form" label-position="top"><el-form-item label="设备名称"><el-input v-model="form.name" /></el-form-item><el-form-item label="设备标识"><el-input v-model="form.code" :disabled="!!form.id" placeholder="留空自动生成" /></el-form-item><el-form-item label="所属产品"><el-select v-model="form.productId" filterable @change="id=>{if(!form.id&&products.find(x=>x.id===id)?.category==='gateway')form.deviceRole='GATEWAY'}"><el-option v-for="x in products" :key="x.id" :label="`${x.name} · ${label(categories,x.category)}`" :value="x.id" /></el-select></el-form-item><div class="form-grid"><el-form-item label="设备角色"><el-select v-model="form.deviceRole"><el-option v-for="(text,key) in deviceRoles" :key="key" :label="text" :value="key" /></el-select></el-form-item><el-form-item label="所属网关"><el-select v-model="form.gatewayId" :disabled="form.deviceRole!=='CHILD'"><el-option v-for="x in gateways" :key="x.device.id" :label="x.device.name" :value="x.device.id" /></el-select></el-form-item></div><el-form-item label="设备状态"><el-select v-model="form.status"><el-option label="已启用" value="ENABLED" /><el-option label="已停用" value="DISABLED" /></el-select></el-form-item><el-form-item label="标签 JSON"><el-input v-model="form.tags" type="textarea" :rows="4" /></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea" :rows="2" /></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存设备</el-button></template></el-dialog>
<el-dialog v-model="credentialDialog" title="设备凭证" width="min(520px, 92vw)"><el-alert title="Secret 只显示这一次，请立即复制并安全保存。" type="warning" :closable="false" /><el-descriptions class="top-gap" :column="1" border><el-descriptions-item label="Access Key"><code>{{credential.accessKey}}</code></el-descriptions-item><el-descriptions-item label="Device Secret"><code class="break-all">{{credential.secret}}</code></el-descriptions-item></el-descriptions><template #footer><el-button @click="credentialDialog=false">关闭</el-button><el-button type="primary" @click="copyCredential">复制凭证</el-button></template></el-dialog></template>
