<script setup>
import { onMounted, reactive, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { api, notifyError, parseJSON, pretty } from '../api'
const emit=defineEmits(['navigate'])
const origin=location.origin
const registry=ref([]), cameras=ref([]), selected=ref(''), guide=ref(null), debugResult=ref('等待发送。'), cameraDialog=ref(false)
const debugPayload=ref(pretty({payload:{properties:{temperature:88.5,smoke:true,battery:92},tags:{cityCode:'city_001',districtCode:'district_01',buildingId:'A',deviceType:'smoke'}}}))
const blank=()=>({cameraId:'',cameraName:'',videoPlatformId:'',projectId:'',cityCode:'',districtCode:'',building:'',floor:'',areaId:'',relatedDeviceIds:'',streamUrl:'',enabled:true})
const camera=reactive(blank()), editing=ref('')
async function load(){try{const [d,c]=await Promise.all([api('/api/v1/device-registry'),api('/api/v1/integrations/video/cameras')]);registry.value=d.items||[];cameras.value=c.items||[];const raw=sessionStorage.getItem('iot:navigation-detail');if(raw){const nav=JSON.parse(raw);selected.value=nav.deviceId||selected.value;sessionStorage.removeItem('iot:navigation-detail')}}catch(e){notifyError(e)}}
async function loadGuide(){if(!selected.value){guide.value=null;return}try{guide.value=await api(`/api/v1/device-registry/${encodeURIComponent(selected.value)}/connection-guide`)}catch(e){notifyError(e)}}
watch(selected,loadGuide)
async function sendDebug(){if(!selected.value)return ElMessage.warning('请先选择设备');try{const body=parseJSON(debugPayload.value,'测试报文');body.messageId=body.messageId||`raw_debug_${Date.now()}`;debugResult.value='发送中…';debugResult.value=pretty(await api(`/api/v1/device-registry/${encodeURIComponent(selected.value)}/debug`,{method:'POST',body:JSON.stringify(body)}));ElMessage.success('数据已进入归档和解析链路')}catch(e){debugResult.value=e.message}}
function openCamera(value){Object.assign(camera,blank(),value?{...value,relatedDeviceIds:(value.relatedDeviceIds||[]).join(',')}:{});editing.value=value?.cameraId||'';cameraDialog.value=true}
async function saveCamera(){try{const value={...camera,relatedDeviceIds:camera.relatedDeviceIds.split(',').map(x=>x.trim()).filter(Boolean)};await api(editing.value?`/api/v1/integrations/video/cameras/${encodeURIComponent(editing.value)}`:'/api/v1/integrations/video/cameras',{method:editing.value?'PUT':'POST',body:JSON.stringify(value)});ElMessage.success('摄像机映射已保存');cameraDialog.value=false;load()}catch(e){notifyError(e)}}
async function copy(kind){if(!guide.value)return;const d=guide.value;let text=pretty(d.payloadTemplate);if(kind==='http')text=`curl -X ${d.http.method} "${location.origin+d.http.url}" -H "Content-Type: application/json" -H "X-Device-Key: ${d.accessKey}" -H "X-Device-Secret: <DEVICE_SECRET>" --data '${JSON.stringify(d.payloadTemplate)}'`;if(kind==='mqtt')text=`Broker: ${d.mqtt.broker}\nTopic: ${d.mqtt.topic}\nToken: POST ${location.origin}${d.mqtt.tokenEndpoint}\nX-Device-Key: ${d.accessKey}`;if(kind==='child')text=pretty(d.gateway.childPayloadTemplate);await navigator.clipboard.writeText(text);ElMessage.success('内容已复制')}
onMounted(()=>load().then(loadGuide))
</script>
<template><div class="integration-grid"><el-card shadow="never" class="surface-card"><template #header><div class="card-header"><strong>设备接入指南</strong><el-button link type="primary" @click="emit('navigate','devices')">管理设备</el-button></div></template><el-select v-model="selected" filterable clearable placeholder="请选择已注册设备"><el-option v-for="row in registry" :key="row.device.id" :label="`${row.device.name} · ${row.device.id}`" :value="row.device.id" /></el-select><el-empty v-if="!guide" description="选择设备后查看 HTTP / MQTT 接入参数" />
<div v-else class="guide-stack"><el-alert title="接入配置已保存" description="设备、产品和协议关系已保存，按下面步骤配置真实设备即可。" type="success" :closable="false" show-icon /><el-steps direction="vertical" :active="3"><el-step title="保存设备凭证" :description="`接入密钥：${guide.accessKey}。设备密钥只在注册或轮换时显示。`" /><el-step title="选择 HTTP 或 MQTT 接入" description="将下面地址、主题和报文模板配置到设备或网关。" /><el-step title="发送数据并验证" description="真实设备发送后可到“原始报文”查看证据链。" /></el-steps><el-card v-if="guide.gateway" shadow="never" class="inner-card"><strong>网关自动注册子设备</strong><p>网关使用自己的凭证上报，报文中的 deviceId 和 productId 指向子设备。</p><pre>{{pretty(guide.gateway.childPayloadTemplate)}}</pre><el-button @click="copy('child')">复制子设备模板</el-button></el-card><el-card shadow="never" class="inner-card"><strong>HTTP 接入</strong><code>{{guide.http.method}} {{origin+guide.http.url}}</code><small>X-Device-Key: {{guide.accessKey}}</small><el-button @click="copy('http')">复制 HTTP 示例</el-button></el-card><el-card shadow="never" class="inner-card"><strong>MQTT 接入</strong><code>{{guide.mqtt.broker}}</code><code>{{guide.mqtt.topic}}</code><el-button @click="copy('mqtt')">复制 MQTT 参数</el-button></el-card><el-card shadow="never" class="inner-card"><strong>报文模板</strong><pre>{{pretty(guide.payloadTemplate)}}</pre><el-button @click="copy('payload')">复制报文模板</el-button></el-card></div></el-card>
<el-card shadow="never" class="surface-card"><template #header><div class="card-header"><strong>在线数据调试</strong><el-tag type="success" round>管理端代理</el-tag></div></template><el-input v-model="debugPayload" type="textarea" :rows="14" /><el-button class="top-gap" type="primary" @click="sendDebug">发送测试数据</el-button><pre>{{debugResult}}</pre></el-card></div>
<el-card shadow="never" class="surface-card table-card top-gap"><template #header><div class="card-header"><strong>视频摄像机映射</strong><el-button type="primary" @click="openCamera()">新增映射</el-button></div></template><el-table :data="cameras" stripe><el-table-column label="摄像机" min-width="180"><template #default="{row}"><b>{{row.cameraName}}</b><small class="subline">{{row.cameraId}}</small></template></el-table-column><el-table-column label="平台 / 项目" min-width="160"><template #default="{row}">{{row.videoPlatformId||'—'}}<small class="subline">{{row.projectId||'—'}}</small></template></el-table-column><el-table-column label="位置" min-width="220"><template #default="{row}">{{[row.cityCode,row.districtCode,row.building,row.floor,row.areaId].filter(Boolean).join(' / ')}}</template></el-table-column><el-table-column label="关联设备" min-width="180"><template #default="{row}">{{(row.relatedDeviceIds||[]).join(', ')||'—'}}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.enabled?'success':'info'" round>{{row.enabled?'已启用':'已停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="openCamera(row)">编辑</el-button></template></el-table-column></el-table></el-card>
<el-dialog v-model="cameraDialog" :title="editing?'编辑摄像机映射':'新增摄像机映射'" width="min(720px, 94vw)"><el-form :model="camera" label-position="top"><div class="form-grid"><el-form-item label="摄像机 ID"><el-input v-model="camera.cameraId" :disabled="!!editing" /></el-form-item><el-form-item label="摄像机名称"><el-input v-model="camera.cameraName" /></el-form-item><el-form-item label="视频平台 ID"><el-input v-model="camera.videoPlatformId" /></el-form-item><el-form-item label="项目 ID"><el-input v-model="camera.projectId" /></el-form-item><el-form-item label="城市编码"><el-input v-model="camera.cityCode" /></el-form-item><el-form-item label="区县编码"><el-input v-model="camera.districtCode" /></el-form-item><el-form-item label="建筑"><el-input v-model="camera.building" /></el-form-item><el-form-item label="楼层"><el-input v-model="camera.floor" /></el-form-item></div><el-form-item label="区域 ID"><el-input v-model="camera.areaId" /></el-form-item><el-form-item label="关联设备 ID（逗号分隔）"><el-input v-model="camera.relatedDeviceIds" /></el-form-item><el-form-item label="视频流地址"><el-input v-model="camera.streamUrl" /></el-form-item><el-form-item><el-switch v-model="camera.enabled" active-text="启用该摄像机" /></el-form-item></el-form><template #footer><el-button @click="cameraDialog=false">取消</el-button><el-button type="primary" @click="saveCamera">保存映射</el-button></template></el-dialog></template>
