<script setup>
import { computed, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api, formatTime, notifyError } from '../api'
import { businessStatuses, label, tagType } from '../labels'

const report=ref(null), loading=ref(false)
const counts=computed(()=>report.value?.counts||{})
async function run(){if(loading.value)return;loading.value=true;try{report.value=await api('/api/v1/ai/health-inspection',{method:'POST',body:'{}'});ElMessage.success('设备健康巡检已完成')}catch(e){notifyError(e)}finally{loading.value=false}}
</script>

<template><div class="inspection-page"><div class="page-toolbar"><div><strong>设备健康巡检</strong><small class="subline">核对设备在线状态、数据新鲜度和活动告警，再生成 AI 处置建议；进入页面不会自动执行</small></div><el-button type="primary" :loading="loading" @click="run">立即巡检</el-button></div><el-card shadow="never" class="surface-card"><el-skeleton v-if="loading&&!report" :rows="5" animated /><template v-else-if="report"><el-alert :title="report.summary" type="info" :closable="false" show-icon /><div class="inspection-counts top-gap"><div><span>设备总数</span><strong>{{counts.total||0}}</strong></div><div class="healthy"><span>状态正常</span><strong>{{counts.healthy||0}}</strong></div><div class="attention"><span>需关注</span><strong>{{counts.attention||0}}</strong></div><div class="critical"><span>高风险</span><strong>{{counts.critical||0}}</strong></div><div class="offline"><span>离线/疑似离线</span><strong>{{counts.offline||0}}</strong></div><div><span>活动告警</span><strong>{{counts.activeAlarms||0}}</strong></div></div><el-card v-if="report.aiAdvice" shadow="never" class="inner-card top-gap"><template #header><strong>AI 巡检建议</strong></template><div class="report-text">{{report.aiAdvice}}</div></el-card><el-alert v-for="warning in report.warnings||[]" :key="warning" class="top-gap" :title="warning" type="warning" :closable="false" /><el-table class="top-gap" :data="report.items||[]" stripe><el-table-column label="设备" min-width="190"><template #default="{row}"><b>{{row.deviceName||row.deviceId}}</b><small class="subline">{{row.deviceId}} · {{row.productId}}</small></template></el-table-column><el-table-column label="业务状态" width="130"><template #default="{row}"><el-tag :type="tagType(row.businessStatus)" round>{{label(businessStatuses,row.businessStatus,row.businessStatus)}}</el-tag></template></el-table-column><el-table-column label="最近上报" min-width="170"><template #default="{row}">{{formatTime(row.lastSeenAt)}}</template></el-table-column><el-table-column label="活动告警" width="100"><template #default="{row}">{{row.activeAlarmCount}}</template></el-table-column><el-table-column label="巡检结论" min-width="280"><template #default="{row}"><el-tag :type="tagType(row.severity)" size="small" round>{{row.severity}}</el-tag><span class="inspection-findings">{{(row.findings||[]).join('；')}}</span></template></el-table-column></el-table></template><el-empty v-else description="点击“立即巡检”开始检查" /></el-card></div></template>
