<script setup>
import { onBeforeUnmount, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api, formatTime, notifyError, pretty } from '../api'
import { alarmLevels, alarmSources, alarmStatuses, alarmType, label, tagType } from '../labels'
const filters=reactive({status:'',level:''}),items=ref([]),loading=ref(false),detail=ref(null),detailVisible=ref(false)
async function load(){loading.value=true;try{const q=new URLSearchParams({status:filters.status,level:filters.level,limit:'100'});const d=await api('/api/v1/alarms?'+q);items.value=d.items||[]}catch(e){notifyError(e)}finally{loading.value=false}}
async function show(id){try{detail.value=await api(`/api/v1/alarms/${encodeURIComponent(id)}`);detailVisible.value=true}catch(e){notifyError(e)}}
async function action(id,value){try{await api(`/api/v1/alarms/${encodeURIComponent(id)}/actions`,{method:'POST',body:JSON.stringify({action:value})});ElMessage.success('操作成功');load()}catch(e){notifyError(e)}}
const realtime=()=>load();onMounted(()=>{load();window.addEventListener('iot:realtime',realtime)});onBeforeUnmount(()=>window.removeEventListener('iot:realtime',realtime))
</script>
<template><div class="page-toolbar"><el-select v-model="filters.status" clearable placeholder="全部状态" @change="load"><el-option v-for="(text,key) in alarmStatuses" :key="key" :label="text" :value="key" /></el-select><el-select v-model="filters.level" clearable placeholder="全部等级" @change="load"><el-option v-for="(text,key) in alarmLevels" :key="key" :label="text" :value="key" /></el-select><el-button type="primary" @click="load">刷新</el-button></div><el-card shadow="never" class="surface-card table-card"><el-table v-loading="loading" :data="items" stripe><el-table-column label="时间" min-width="170"><template #default="{row}">{{formatTime(row.lastTriggeredAt)}}</template></el-table-column><el-table-column label="设备 / 来源" min-width="190"><template #default="{row}"><b>{{row.deviceName||row.deviceId}}</b><small class="subline">{{label(alarmSources,row.source,'其他来源')}}</small></template></el-table-column><el-table-column label="告警类型" min-width="150"><template #default="{row}">{{alarmType(row.alarmType)}}</template></el-table-column><el-table-column label="等级" width="90"><template #default="{row}"><el-tag :type="tagType(row.alarmLevel)" round>{{label(alarmLevels,row.alarmLevel,'未设置')}}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="tagType(row.status)" round>{{label(alarmStatuses,row.status)}}</el-tag></template></el-table-column><el-table-column label="操作" width="210" align="center"><template #default="{row}"><div class="table-actions"><el-button plain type="primary" @click="show(row.alarmId)">查看详情</el-button><template v-if="['ACTIVE','ACKED'].includes(row.status)"><el-button plain type="warning" @click="action(row.alarmId,'ACKED')">确认</el-button><el-button plain type="danger" @click="action(row.alarmId,'CLOSED')">关闭</el-button></template></div></template></el-table-column></el-table></el-card><el-dialog v-model="detailVisible" title="告警详情" width="min(720px, 94vw)"><el-descriptions v-if="detail" :column="1" border><el-descriptions-item label="告警编号">{{detail.alarmId}}</el-descriptions-item><el-descriptions-item label="设备">{{detail.deviceName||detail.deviceId}}</el-descriptions-item><el-descriptions-item label="告警类型">{{alarmType(detail.alarmType)}}</el-descriptions-item><el-descriptions-item label="等级 / 状态"><el-tag :type="tagType(detail.alarmLevel)">{{label(alarmLevels,detail.alarmLevel)}}</el-tag> {{label(alarmStatuses,detail.status)}}</el-descriptions-item><el-descriptions-item label="来源">{{label(alarmSources,detail.source,'其他来源')}}</el-descriptions-item><el-descriptions-item label="首次发生">{{formatTime(detail.firstTriggeredAt)}}</el-descriptions-item><el-descriptions-item label="最后发生">{{formatTime(detail.lastTriggeredAt)}}</el-descriptions-item><el-descriptions-item label="触发次数">{{detail.triggerCount}}</el-descriptions-item></el-descriptions><pre>{{pretty(detail)}}</pre></el-dialog></template>
