<script setup>
import { onMounted, ref, watch } from 'vue'
import { ElMessage } from 'element-plus'
import { api, notifyError, parseJSON, pretty } from '../api'
const emit=defineEmits(['navigate'])
const origin=location.origin
const registry=ref([]), selected=ref(''), guide=ref(null), debugResult=ref('等待发送。')
const debugPayload=ref(pretty({payload:{properties:{temperature:88.5,smoke:true,battery:92},tags:{cityCode:'city_001',districtCode:'district_01',buildingId:'A',deviceType:'smoke'}}}))
async function load(){try{const d=await api('/api/v1/device-registry');registry.value=d.items||[];const raw=sessionStorage.getItem('iot:navigation-detail');if(raw){const nav=JSON.parse(raw);selected.value=nav.deviceId||selected.value;sessionStorage.removeItem('iot:navigation-detail')}}catch(e){notifyError(e)}}
async function loadGuide(){if(!selected.value){guide.value=null;return}try{guide.value=await api(`/api/v1/device-registry/${encodeURIComponent(selected.value)}/connection-guide`)}catch(e){notifyError(e)}}
watch(selected,loadGuide)
async function sendDebug(){if(!selected.value)return ElMessage.warning('请先选择设备');try{const body=parseJSON(debugPayload.value,'测试报文');body.messageId=body.messageId||`raw_debug_${Date.now()}`;debugResult.value='发送中…';debugResult.value=pretty(await api(`/api/v1/device-registry/${encodeURIComponent(selected.value)}/debug`,{method:'POST',body:JSON.stringify(body)}));ElMessage.success('数据已进入归档和解析链路')}catch(e){debugResult.value=e.message}}
async function copy(kind){if(!guide.value)return;const d=guide.value;let text=pretty(d.payloadTemplate);if(kind==='http')text=`curl -X ${d.http.method} "${location.origin+d.http.url}" -H "Content-Type: application/json" -H "X-Device-Key: ${d.accessKey}" -H "X-Device-Secret: <DEVICE_SECRET>" --data '${JSON.stringify(d.payloadTemplate)}'`;if(kind==='mqtt')text=`Broker: ${d.mqtt.broker}\nTopic: ${d.mqtt.topic}\nToken: POST ${location.origin}${d.mqtt.tokenEndpoint}\nX-Device-Key: ${d.accessKey}`;if(kind==='child')text=pretty(d.gateway.childPayloadTemplate);await navigator.clipboard.writeText(text);ElMessage.success('内容已复制')}
onMounted(()=>load().then(loadGuide))
</script>
<template><div class="integration-grid"><el-card shadow="never" class="surface-card"><template #header><div class="card-header"><strong>设备连接指南</strong><el-button plain type="primary" @click="emit('navigate','devices')">管理设备</el-button></div></template><el-select v-model="selected" filterable clearable placeholder="请选择已注册设备"><el-option v-for="row in registry" :key="row.device.id" :label="`${row.device.name} · ${row.device.id}`" :value="row.device.id" /></el-select><el-empty v-if="!guide" description="选择设备后查看 HTTP / MQTT 上报参数" />
<div v-else class="guide-stack"><el-alert title="接入配置已保存" description="设备、产品和协议关系已保存，按下面步骤配置真实设备即可。" type="success" :closable="false" show-icon /><el-steps direction="vertical" :active="3"><el-step title="保存设备凭证" :description="`接入密钥：${guide.accessKey}。设备密钥只在注册或轮换时显示。`" /><el-step title="选择 HTTP 或 MQTT 接入" description="将下面地址、主题和报文模板配置到设备或网关。" /><el-step title="发送数据并验证" description="真实设备发送后可到“原始报文”查看证据链。" /></el-steps><el-card v-if="guide.gateway" shadow="never" class="inner-card"><strong>网关自动注册子设备</strong><p>网关使用自己的凭证上报，报文中的 deviceId 和 productId 指向子设备。</p><pre>{{pretty(guide.gateway.childPayloadTemplate)}}</pre><el-button @click="copy('child')">复制子设备模板</el-button></el-card><el-card shadow="never" class="inner-card"><strong>HTTP 接入</strong><code>{{guide.http.method}} {{origin+guide.http.url}}</code><small>X-Device-Key: {{guide.accessKey}}</small><el-button @click="copy('http')">复制 HTTP 示例</el-button></el-card><el-card shadow="never" class="inner-card"><strong>MQTT 接入</strong><code>{{guide.mqtt.broker}}</code><code>{{guide.mqtt.topic}}</code><el-button @click="copy('mqtt')">复制 MQTT 参数</el-button></el-card><el-card shadow="never" class="inner-card"><strong>报文模板</strong><pre>{{pretty(guide.payloadTemplate)}}</pre><el-button @click="copy('payload')">复制报文模板</el-button></el-card></div></el-card>
<el-card shadow="never" class="surface-card"><template #header><div class="card-header"><strong>数据联调（可选）</strong><el-tag type="warning" round>不会代替真实设备上报</el-tag></div></template><el-alert title="这里仅用于验证协议包、归档和规则链路" description="真实设备上报后请到原始报文查看解析结果；测试数据也会进入同一条链路并留下审计记录。" type="info" :closable="false" show-icon /><el-input class="top-gap" v-model="debugPayload" type="textarea" :rows="14" /><el-button class="top-gap" type="primary" @click="sendDebug">发送测试数据</el-button><pre>{{debugResult}}</pre></el-card></div>
</template>
