<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { api, notifyError, parseJSON, pretty } from '../api'
import { enabledStatuses, label, parsers, tagType } from '../labels'
const items=ref([]), testing=ref(false), result=ref('选择或保存一个协议包后可进行调试。')
const blank=()=>({id:'',name:'',version:'1.0.0',protocol:'json',transport:'MQTT',payloadFormat:'json',parserType:'custom_json_parser',status:'DRAFT',config:'{}',description:''})
const form=reactive(blank()), sample=ref('{"data":{"temp":805,"smoke":true},"kind":"smoke","occurredAt":1710000000}'), scriptSource=ref('function parse(raw) {\n  return {\n    properties: raw.payload.properties || {},\n    tags: raw.payload.tags || {},\n    messageType: "PROPERTY_REPORT"\n  }\n}')
async function load(){try{const d=await api('/api/v1/protocol-packages');items.value=d.items||[]}catch(e){notifyError(e)}}
function reset(){Object.assign(form,blank());scriptSource.value='function parse(raw) {\n  return {\n    properties: raw.payload.properties || {},\n    tags: raw.payload.tags || {},\n    messageType: "PROPERTY_REPORT"\n  }\n}';result.value='选择或保存一个协议包后可进行调试。'}
function edit(x){Object.assign(form,{...x,config:pretty(x.config||{})});scriptSource.value=x.config?.source||scriptSource.value}
function parserChanged(value){if(value==='configurable_json_parser'){form.protocol='json';form.payloadFormat='json';form.config=pretty({properties:{temperature:{path:'$.data.temp',type:'number',scale:0.1},smoke:'$.data.smoke'},tags:{deviceType:'$.kind'},timestampPath:'$.occurredAt',timestampUnit:'s'});sample.value='{"data":{"temp":805,"smoke":true},"kind":"smoke","occurredAt":1710000000}'}else if(value==='configurable_hex_parser'){form.protocol='config-hex';form.payloadFormat='hex';form.config=pretty({startHex:'AA',endHex:'55',checksum:'sum8',checksumStartOffset:1,fields:[{name:'temperature',offset:1,length:2,type:'int16',endian:'little',scale:0.1}]});sample.value='AA 20 03 00 23 55'}else if(value==='javascript_sandbox_parser'){form.protocol='javascript';form.config='';sample.value='{"properties":{"temperature":88.5,"smoke":true},"tags":{"deviceType":"smoke"}}'}}
async function loadScriptFile(event){const file=event.target.files?.[0];if(!file)return;if(file.size>65536){ElMessage.error('解析脚本不能超过 64 KiB');event.target.value='';return}try{scriptSource.value=await file.text();ElMessage.success('解析脚本已载入')}catch(e){notifyError(e)}finally{event.target.value=''}}
async function save(){try{const config=form.parserType==='javascript_sandbox_parser'?{source:scriptSource.value}:parseJSON(form.config,'配置 JSON'),v={...form,config},editing=!!form.id,d=await api(editing?`/api/v1/protocol-packages/${encodeURIComponent(form.id)}`:'/api/v1/protocol-packages',{method:editing?'PUT':'POST',body:JSON.stringify(v)});ElMessage.success('协议包已保存');await load();edit(items.value.find(x=>x.id===d.id)||d)}catch(e){notifyError(e)}}
async function runTest(){if(!form.id)return ElMessage.warning('请先选择或保存协议包');testing.value=true;try{const payload=form.payloadFormat==='hex'?sample.value.trim():parseJSON(sample.value,'样本载荷');result.value=pretty(await api(`/api/v1/protocol-packages/${encodeURIComponent(form.id)}/test`,{method:'POST',body:JSON.stringify({payload})}))}catch(e){result.value=e.message}finally{testing.value=false}}
onMounted(load)
</script>
<template><div class="workspace-grid protocol"><el-card shadow="never" class="surface-card"><template #header><div class="card-header"><strong>协议包版本</strong><el-button type="primary" @click="reset">新建协议包</el-button></div></template><div class="catalog-list"><button v-for="item in items" :key="item.id" @click="edit(item)"><span><b>{{item.name}}</b><small>{{item.id}} · 版本 {{item.version}}</small></span><span><el-tag :type="tagType(item.status)" round>{{label(enabledStatuses,item.status)}}</el-tag><small>{{label(parsers,item.parserType,'其他解析器')}}</small></span></button><el-empty v-if="!items.length" description="暂无协议包" /></div></el-card>
<el-card shadow="never" class="surface-card"><template #header><div class="card-header"><strong>{{form.id?`协议包 · ${form.name}`:'协议包工作台'}}</strong><el-tag type="success" round>可配置解析</el-tag></div></template><el-alert title="协议解析可以通过配置或受限脚本扩展" description="JSON / 固定字段十六进制可直接配置；其他设备可上传纯解析 JavaScript，无需重新部署 API。脚本不能访问文件、网络或平台服务。" type="info" :closable="false" show-icon /><el-form :model="form" label-position="top" class="top-gap"><div class="form-grid"><el-form-item label="名称"><el-input v-model="form.name" /></el-form-item><el-form-item label="版本"><el-input v-model="form.version" /></el-form-item><el-form-item label="协议标识"><el-input v-model="form.protocol" /></el-form-item><el-form-item label="传输方式"><el-select v-model="form.transport"><el-option v-for="x in ['MQTT','HTTP','TCP','MODBUS_TCP']" :key="x" :label="x" :value="x" /></el-select></el-form-item><el-form-item label="载荷格式"><el-select v-model="form.payloadFormat"><el-option label="结构化文本" value="json" /><el-option label="十六进制" value="hex" /></el-select></el-form-item><el-form-item label="解析器"><el-select v-model="form.parserType" @change="parserChanged"><el-option v-for="(text,key) in parsers" :key="key" :label="text" :value="key" /></el-select></el-form-item></div><el-form-item label="发布状态"><el-select v-model="form.status"><el-option label="草稿" value="DRAFT" /><el-option label="已发布" value="PUBLISHED" /><el-option label="已停用" value="DISABLED" /></el-select></el-form-item><el-form-item v-if="form.parserType==='javascript_sandbox_parser'" label="解析脚本"><input type="file" accept=".js,text/javascript" @change="loadScriptFile" /><el-input v-model="scriptSource" class="top-gap" type="textarea" :rows="12" /><small class="subline">脚本必须定义 `function parse(raw)`，最大 64 KiB；可使用 `hexToBytes()` 和 `toInt()`。</small></el-form-item><el-form-item v-else label="配置 JSON"><el-input v-model="form.config" type="textarea" :rows="8" /><small class="subline">JSON 映射示例：`$.data.temperature`；十六进制字段使用 offset、length、type、endian、scale。</small></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea" :rows="2" /></el-form-item><el-button type="primary" @click="save">保存协议包</el-button></el-form><el-divider content-position="left">解析调试</el-divider><el-input v-model="sample" type="textarea" :rows="5" /><el-button class="top-gap" :loading="testing" @click="runTest">运行解析</el-button><pre>{{result}}</pre></el-card></div></template>
