<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { api, notifyError, parseJSON, pretty } from '../api'
import { alarmLevels, alarmType, alarmTypes, label, tagType } from '../labels'
const rules=ref([]),products=ref([]),dialog=ref(false),prompt=ref(''),draft=ref(null),drafting=ref(false),draftError=ref('')
const blank=()=>({id:'',name:'',alarmType:'FIRE_RISK',level:'HIGH',productId:'',match:'all',expression:'',conditions:pretty([{field:'temperature',operator:'>',value:80}]),recovery:'[]',durationSeconds:0,enabled:true})
const form=reactive(blank())
async function load(){try{const [r,p]=await Promise.all([api('/api/v1/rules'),api('/api/v1/products')]);rules.value=r.items||[];products.value=p.items||[]}catch(e){notifyError(e)}}
function open(value){Object.assign(form,blank(),value?{...value,conditions:pretty(value.conditions||(value.expression?[]:[{field:'temperature',operator:'>',value:80}])),recovery:pretty(value.recovery||[])}:{});dialog.value=true}
async function save(){try{const value={...form,expression:form.expression.trim(),conditions:parseJSON(form.conditions||'[]','触发条件'),recovery:parseJSON(form.recovery||'[]','恢复条件'),durationSeconds:Number(form.durationSeconds)||0};if(!Array.isArray(value.conditions)||!Array.isArray(value.recovery))throw new Error('条件必须是 JSON 数组');if(!value.expression&&!value.conditions.length)throw new Error('Gengine 表达式与条件 JSON 至少填写一种');const id=value.id;delete value.id;await api(id?`/api/v1/rules/${encodeURIComponent(id)}`:'/api/v1/rules',{method:id?'PUT':'POST',body:JSON.stringify(value)});ElMessage.success('规则已保存');dialog.value=false;load()}catch(e){notifyError(e)}}
async function remove(id){try{await ElMessageBox.confirm('删除后规则将不再参与告警计算，历史告警仍会保留。','删除规则',{type:'warning'});await api(`/api/v1/rules/${encodeURIComponent(id)}`,{method:'DELETE'});ElMessage.success('规则已删除');load()}catch(e){if(e!=='cancel')notifyError(e)}}
async function createDraft(){if(!prompt.value.trim()){draftError.value='请输入规则要求';return}drafting.value=true;draftError.value='';draft.value=null;try{const d=await api('/api/v1/ai/rule-draft',{method:'POST',body:JSON.stringify({text:prompt.value.trim()})});draft.value=d.draft}catch(e){draftError.value=e?.message||String(e);notifyError(e)}finally{drafting.value=false}}
function useDraft(){open({...draft.value,id:'',enabled:false})}
onMounted(load)
</script>
<template><div class="rules-grid"><el-card shadow="never" class="surface-card"><template #header><div class="card-header"><strong>规则列表</strong><el-button type="primary" @click="open()">手动添加规则</el-button></div></template><div class="rule-list"><div v-for="item in rules" :key="item.id" class="rule-item"><div><b>{{item.name}}</b><small>{{alarmType(item.alarmType)}} · {{label(alarmLevels,item.level,'未设置')}} · {{item.enabled?'已启用':'草稿'}} · 版本 {{item.version}}</small></div><div><el-tag :type="tagType(item.level)" round>{{label(alarmLevels,item.level)}}</el-tag><el-button plain type="primary" @click="open(item)">编辑</el-button><el-button plain type="danger" @click="remove(item.id)">删除</el-button></div></div><el-empty v-if="!rules.length" description="暂无规则，可手动添加或使用 AI 生成草稿" /></div></el-card><el-card shadow="never" class="surface-card"><template #header><strong>AI 规则草稿</strong></template><el-input v-model="prompt" type="textarea" :rows="6" placeholder="例如：A 区烟感温度超过 80 度且烟雾为 true，触发高级别火警。" /><el-button class="top-gap" type="primary" :loading="drafting" @click="createDraft">生成草稿</el-button><el-alert v-if="draftError" class="top-gap" type="error" :closable="false" show-icon title="规则草稿生成失败" :description="draftError" /><el-card v-if="draft" shadow="never" class="inner-card top-gap"><el-descriptions :column="1"><el-descriptions-item label="规则名称">{{draft.name||'未命名'}}</el-descriptions-item><el-descriptions-item label="告警类型">{{alarmType(draft.alarmType)}}</el-descriptions-item><el-descriptions-item label="告警等级">{{label(alarmLevels,draft.level,'未设置')}}</el-descriptions-item><el-descriptions-item label="启用状态">待人工确认</el-descriptions-item></el-descriptions><el-button @click="useDraft">载入草稿并编辑</el-button></el-card></el-card></div>
<el-dialog v-model="dialog" :title="form.id?`编辑规则 · ${form.name}`:'手动添加规则'" width="min(760px, 94vw)"><el-form :model="form" label-position="top"><el-form-item label="规则名称"><el-input v-model="form.name" /></el-form-item><div class="form-grid"><el-form-item label="告警类型"><el-select v-model="form.alarmType"><el-option v-for="(text,key) in alarmTypes" :key="key" :label="text" :value="key" /></el-select></el-form-item><el-form-item label="告警等级"><el-select v-model="form.level"><el-option v-for="(text,key) in alarmLevels" :key="key" :label="text" :value="key" /></el-select></el-form-item><el-form-item label="所属产品（可选）"><el-select v-model="form.productId" clearable><el-option v-for="x in products" :key="x.id" :label="x.name" :value="x.id" /></el-select></el-form-item><el-form-item label="条件关系"><el-select v-model="form.match"><el-option label="全部满足" value="all" /><el-option label="任一满足" value="any" /></el-select></el-form-item></div><el-form-item label="Gengine 表达式（与条件 JSON 二选一）"><el-input v-model="form.expression" type="textarea" :rows="3" placeholder='Properties["temperature"] > 80 && Properties["smoke"] == true' /></el-form-item><el-form-item label="触发条件 JSON"><el-input v-model="form.conditions" type="textarea" :rows="6" /></el-form-item><el-form-item label="恢复条件 JSON"><el-input v-model="form.recovery" type="textarea" :rows="4" /></el-form-item><div class="form-grid"><el-form-item label="持续秒数"><el-input-number v-model="form.durationSeconds" :min="0" /></el-form-item><el-form-item label="保存后状态"><el-switch v-model="form.enabled" active-text="立即启用" inactive-text="保存为草稿" /></el-form-item></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存规则</el-button></template></el-dialog></template>
